Repository rachel5004/ShareToDolistProject, pull requests merged in 2021-02, with the labels that each got.

#12 Mainpage conflict
  ShareToDoList/main.py
  ShareToDoList/templates/signin.html
  ShareToDoList/templates/signin_success.html
Labels: enhancement

#14 Frontend
  .gitignore
  ShareToDoList/main.py
  ShareToDoList/static/components.js
  ShareToDoList/static/dist/bundle.js
  ShareToDoList/static/js/components/navButton.js
  ShareToDoList/static/js/pages/clock.js
  ShareToDoList/static/main.css
  ShareToDoList/static/package-lock.json
  ShareToDoList/static/package.json
  ShareToDoList/static/webpack.config.js
  ShareToDoList/templates/layout.html
  ShareToDoList/templates/login.html
  ShareToDoList/templates/main_need_login.html
  ShareToDoList/templates/signin.html
  ShareToDoList/templates/static/brand/bootstrap-logo-white.svg
  ShareToDoList/templates/static/brand/bootstrap-logo.svg
  ShareToDoList/templates/static/dist/css/bootstrap.min.css
  ShareToDoList/templates/static/dist/css/bootstrap.min.css.map
  ShareToDoList/templates/static/dist/css/bootstrap.rtl.min.css
  ShareToDoList/templates/static/dist/css/bootstrap.rtl.min.css.map
  ShareToDoList/templates/static/dist/js/bootstrap.bundle.min.js
  ShareToDoList/templates/static/dist/js/bootstrap.bundle.min.js.map
  ShareToDoList/templates/static/images/todoLogo.png
Labels: Requirements

#22 :lipstick: fix room list
  ShareToDoList/templates/main.html
Labels: bug

#25 :whale: docker-compose
  README.md
  ShareToDoList/Dockerfile
  ShareToDoList/main.py
  ShareToDoList/requirements.txt
  docker-compose.yml
  mysql/sqls/initialize.sql
Labels: Requirements

#27 :sparkles: Front Email validate AJAX 추가
  ShareToDoList/main.py
  ShareToDoList/static/js/pages/signin.js
  ShareToDoList/templates/signin.html
Labels: Requirements
